image: alpine/edge
packages:
  - go
  - make
sources:
  - https://git.sr.ht/~bacardi55/cleanABag
tasks:
  - setup: |
      cd cleanABag
      make dependencies
  - build: |
      cd cleanABag
      make buildAll
artifacts:
  - cleanABag/bin/cleanABag_linux_amd64
  - cleanABag/bin/cleanABag_linux_arm
  - cleanABag/bin/cleanABag_linux_arm64
  - cleanABag/bin/cleanABag_linux_386
triggers:
  - action: email
    condition: always
    to: bac@rdi55.pl
